language: node_js

node_js:
  - 0.10

before_install:
  # GUI for real browsers.
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

install:
  - npm install
  # Install and build all sub-projects.
  - ./node_modules/.bin/gulp install
  - ./node_modules/.bin/gulp build

script:
  # Root level checks.
  - ./node_modules/.bin/gulp check:ci
  # Sub-project checks.
  - cd full/amd
  - ./node_modules/.bin/grunt check:ci
  - cd ../..
  - cd skeleton/amd
  - ./node_modules/.bin/grunt check:ci
  - cd ../..
