language: node_js

node_js:
  - 0.10

before_install:
  # GUI for real browsers.
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

install:
  - cd full/amd
  - npm install
  - ./node_modules/.bin/grunt build

script:
  - cd full/amd
  - ./node_modules/.bin/grunt check:ci
